import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";
import assert from "node:assert/strict";

const require = createRequire(import.meta.url);
const manifest = JSON.parse(readFileSync("package.json", "utf8"));
const pending = Object.keys(manifest.dependencies);
const visited = new Set();
const notices = ["Atlyn Marimekko - third-party runtime dependency notices",
    "Generated from the locked, installed dependency tree. The SDK API and its semver dependency are included conservatively; type-only code may be elided from the bundle.",
    "These notices license the identified third-party code only, not the Atlyn product.\n"];
while (pending.length) {
    const name = pending.shift();
    if (visited.has(name)) continue;
    visited.add(name);
    const packagePath = require.resolve(`${name}/package.json`);
    const pkg = JSON.parse(readFileSync(packagePath, "utf8"));
    assert.ok(["MIT", "ISC"].includes(pkg.license), `Review unapproved license for ${name}`);
    const files = readdirSync(dirname(packagePath));
    const licenseFile = files.find(file => /^licen[cs]e(\.(md|txt))?$/i.test(file));
    assert.ok(licenseFile, `Missing license: ${name}`);
    notices.push(`===== ${pkg.name} ${pkg.version} (${pkg.license}) =====`,
        typeof pkg.repository === "string" ? pkg.repository : pkg.repository?.url ?? "",
        readFileSync(join(dirname(packagePath), licenseFile), "utf8").trim(), "");
    pending.push(...Object.keys(pkg.dependencies ?? {}));
}
const globalize = readFileSync(require.resolve("powerbi-visuals-utils-formattingutils/lib/globalize/globalize.js"), "utf8");
const cultures = readFileSync(require.resolve("powerbi-visuals-utils-formattingutils/lib/globalize/globalize.cultures.js"), "utf8");
const header = text => text.slice(0, text.indexOf("*/") + 2);
assert.match(header(globalize), /Dual licensed under the MIT or GPL/);
const mitLicense = readFileSync(require.resolve("powerbi-visuals-utils-formattingutils/LICENSE"), "utf8");
const permissionStart = mitLicense.indexOf("Permission is hereby");
assert.ok(permissionStart >= 0, "MIT license text not found");
notices.push("===== Bundled Globalize and culture data: MIT option selected =====",
    header(globalize), header(cultures),
    mitLicense.slice(permissionStart).trim(),
    "Upstream: https://github.com/globalizejs/globalize", "");
const content = notices.join("\n").trimEnd() + "\n";
const generated = `// Generated by npm run notices. Do not edit manually.\nexport const NOTICES = ${JSON.stringify(content)};\n`;
if (process.argv.includes("--check")) {
    assert.equal(readFileSync("THIRD-PARTY-NOTICES.txt", "utf8"), content, "Regenerate dependency notices");
    assert.equal(readFileSync("src/notices.ts", "utf8"), generated, "Regenerate embedded notices");
    console.log(`Notices match ${visited.size} dependency packages and bundled Globalize.`);
} else {
    writeFileSync("THIRD-PARTY-NOTICES.txt", content);
    writeFileSync("src/notices.ts", generated);
    console.log(`Generated and embedded notices for ${visited.size} dependency packages and bundled Globalize.`);
}
